### ISSUE TITLE
meta-issue

### ISSUE THREAD

**Issue by jaredgalloway** [matsengrp/gcreplay#13]
Keeping this as a list of potential  changes / bugs / improvements to pipeline I've come across along the way but been too busy to address completely. Being a little lazy here - these should each get their own issue if we want to pursue them - but this will be a good place to discuss worth-while changes and goals. 

- [ ] FACS Cell Sort Data to be included with each observed BCR?
- [ ] `TorchDMS` integration for phenotype prediction (pending approval for analysis and training heuristics which work for our purposes)
- [ ] Example Data. What would be a good testing subset to include with the repo for quick investigation to parameter / input changes? It would also be good to have a testing set that confirms exact input to output mapping for changes we make along the way.
- [ ] Extra parameters, there's already an issue for this but there's a few more hardcoded parameters within the pipeline that should be pulled to a config file
- [ ] Partis error when when running non-germline annotation. I'm not sure this is still an issue but will need to be investigated if we want to generalize the pipeline for all GC seq
- [ ] publishing script / documentation. We're currently using git lfs but seem to run into issues. could we document or make a script for easily publishing new results.
- [ ] Partis prediction of `IGK` on sequences from fasta files that we're curated from the `cudadapt` step and assigned to as heavy chain sequences. I think there were only a few but non the less this caused problems and I had to throw them
- [ ] Silent mutations - I'm not sure if / how partis reports these, or if we should be doing so. We look for mutations directly by string matching only at the AA level.
- [ ] Updating bioinformatics software. `fastx-tools` is extremely outdated. We need to update this at some point.
